### ISSUE TITLE
add "Enhancing Complex Question Answering over Knowledge Graphs through Evidence Pattern Retrieval"

### ISSUE THREAD

**Issue by xixi019** [KGQA/leaderboard#225] opened 2024-02-14 14:22 UTC
https://arxiv.org/pdf/2402.02175.pdf

Interesting work in information retrieval based methods and surpass the semantic parsing based systems.

**Comment by debayan** [comment] 2024-06-24 09:33
Closing as duplicate of https://github.com/KGQA/leaderboard/issues/226

**Closed as completed** 2024-06-24 09:34 UTC
